part of number;

/**
 * *Uncertainty*
   A Quantity object optionally includes an uncertainty, as quantities are
   often determined by measurement and therefore are only accurate within
   the capabilities of the measuring devices or techniques.  Internally,
   the uncertainty of a quantity is modeled as a Normal (Gaussian) distribution.
   The shape of this "bell curve" distribution is captured by a single value:
   the relative standard uncertainty.  This method of expressing uncertainty is
   used for all physical constants and is accepted for general use with all
   quantities (because quantities, as measurable entities, all follow the same
   logic for representing the uncertainty generated by the combination of
   values from many different experiments).  The relative standard uncertainty
   corresponds to an approximately 68% confidence level (that the quantity's
   value is in the stated range).  For different confidence levels, alternative
   coverage factors may be used (k=2 ~95%; k=3 ~99%).  Uncertainty calculations
   may be switched on or off as desired.  It is automatically on if the Quantity
   is constructed with any uncertainty and off otherwise.  The setCalcUncertainty
   method may be called at any point to enable/disable this capability.<p>
 * 
 */
abstract class Number {
  
  // num, 
  Object _value;
  
  /**
   * Sets whether or not uncertainty is to be calculated within 
   * mathematical methods.
   */
  bool _calcUncertainty = false;
  
  /** The relative uncertainty. */
  double _ur = 0.0;
  
  Object get value => _value;

  set value(Number number);
  
  

  /**
     Returns the relative standard uncertainty in this Quantity object's value.
  <p>
     <b>Notes:</b><br>
     (1) Relative standard uncertainty is defined as the standard uncertainty
     divided by the absolute value of the quantity.  Standard uncertainty, in turn,
     is defined as the uncertainty (of a measurement result) by an estimated
     standard deviation, which is equal to the positive square root of the
     estimated variance.  One standard deviate in a Normal distribution
     corresponds to a coverage factor of 1 (k=1) and a confidence of approximately
     68%.
  <p>
     * @return the relative uncertainty
  */
  double get relativeUncertainty => _ur;


  /**
     Sets the relative standard uncertainty in this Quantity object's value.
  <p>
     <b>Notes:</b><br>
     (1) Will throw an ImmutableQuantityException (a RuntimeException) if this
     Quantity is in an immutable state.<br>
     (2) Relative standard uncertainty is defined as the standard uncertainty
     divided by the absolute value of the quantity.  Standard uncertainty, in turn,
     is defined as the uncertainty (of a measurement result) by an estimated
     standard deviation, which is equal to the positive square root of the
     estimated variance.  One standard deviate in a Normal distribution
     corresponds to a coverage factor of 1 (k=1) and a confidence of approximately
     68%.
  <p>
     * @param ur the relative uncertainty
  */
  set relativeUncertainty(double value) {
    if(immutable) throw new ImmutableQuantityException("In Quantity.setRelativeUncertainty",this);
    this._ur = value;
  }

}
